### ISSUE TITLE
在浏览器打开问题

### ISSUE THREAD

**Issue by yuzaoqian** [2277419213/vue-cropper-h5#15]
.wrapper{
             height: calc(100vh - 21.333vw -50px);
 }
这个好像没有处理浏览器底部选择栏问题，导致运行h5用浏览器打开项目后 底部按钮区域被浏览器底部tabbar遮盖住了

**Comment by 2277419213** [comment]
每个浏览器底部菜单栏的高度都是不固定的，推荐把按钮放在顶部，用这个控制ceilbutton，详情查看文档
