### ISSUE TITLE
组件以CDN方式使用可能会导致内置事件无法响应

### ISSUE THREAD

**Issue by awen1988** [2277419213/vue-cropper-h5#2]
SPA大行其道，现在应该很少有人用CDN方式使用组件了，但是作为一个前后端都要干的技术员，还是觉得jQuery那套引入就用真香，这个组件我试了一下非常棒，也支持cdn方式使用，直接使用dist/index.js即可，但是有个问题，部分情况会导致内置事件无响应，未经过其他场景验证，临时解决方案如下：
1、打开dist/index.js搜索关键词“getbase64Data”、“getblobData”并替换成小写，我直接替换成了base64和blob这样就可以响应事件了。
2、如遇到组件无法原样输出未渲染的情况，可以将标签改为小写-的形式
`<h5-cropper :option="option" @base64="getbase64Data" @blob="getblobData"></h5-cropper>`

**Comment by 2277419213** [comment]
感谢您的建议，下一个版本我会将内置的方法名称改成小写，谢谢
