### ISSUE TITLE
canceltailor在cdn引入的情况下不能触发

### ISSUE THREAD

**Issue by lizhengzeng1993** [2277419213/vue-cropper-h5#20]

**Comment by 2277419213** [comment]
检查一下cdn的版本对不对哦，刚试了没有问题
<script src="https://cdn.jsdelivr.net/npm/vue-cropper-h5@1.2.3/dist/index.min.js"></script>

**Comment by lizhengzeng1993** [comment]
哈哈，看了眼是用的1.1.9这个版本，换成新的版本可以了
