### ISSUE TITLE
接口 那栏目的咋么使用啊

### ISSUE THREAD

**Issue by lllomh** [2277419213/vue-cropper-h5#28]
接口 那栏目的咋么使用啊

**Comment by 2277419213** [comment]
ref 
this.$refs.cropper.loadFile(target.files[0])
可以看这个demo
https://github.com/2277419213/vue-cropper-h5/blob/master/example/cdn/hide-input.html

**Comment by lllomh** [comment]
感谢大佬救急&nbsp; &nbsp;感恩
&nbsp;

            &nbsp;&nbsp;&nbsp;&nbsp; 

     
                                   lllomh                       
                        Professional IT               
      
                     Email：                 ***@***.***               
               Network company：                 http://bhw.lllomh.com/               
      
     
    
   


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年5月20日(星期四) 下午5:49
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [2277419213/vue-cropper-h5] 接口 那栏目的咋么使用啊 (#28)





 
ref
 this.$refs.cropper.loadFile(target.files[0])
 可以看这个demo
 https://github.com/2277419213/vue-cropper-h5/blob/master/example/cdn/hide-input.html
