### ISSUE TITLE
iphone11自带浏览器 裁图界面的操作按钮显示不出来

### ISSUE THREAD

**Issue by Xyuan-abs** [2277419213/vue-cropper-h5#36]
iphone11自带浏览器 裁图界面的操作按钮显示不出来

**Comment by 2277419213** [comment]
被操作栏挡住了，这个ceilbutton属性设置为true，把按钮放置到上方就好了

**Comment by Xyuan-abs** [comment]
操作栏移至顶部后，截图框整体被挤下去了。操作栏还是脱离文档流比较好吧
------------------ 原始邮件 ------------------
发件人: 居里栈栈 ***@***.***&gt;
发送时间: 2021年9月1日 17:22
收件人: 2277419213/vue-cropper-h5 ***@***.***&gt;
抄送: Xyuan-abs ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[2277419213/vue-cropper-h5] iphone11自带浏览器 裁图界面的操作按钮显示不出来 (#36)





 
被操作栏挡住了，这个ceilbutton属性设置为true，把按钮放置到上方就好了
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Xyuan-abs** [comment]
![image](https://user-images.githubusercontent.com/64180387/132184718-72670407-572f-4da4-99f0-c6b7fcda8dd3.png)
使用fixed可解决
