### ISSUE TITLE
vue3调用loadFile方法时报loadFile is not a function

### ISSUE THREAD

**Issue by Xyuan-abs** [2277419213/vue-cropper-h5#41]
![image](https://user-images.githubusercontent.com/64180387/140899880-5dce727b-3b51-476a-a6c2-8f3b6ebaeb23.png)
![image](https://user-images.githubusercontent.com/64180387/140900850-02861a10-ac13-48f1-afd7-2210d14ac4fb.png)
![image](https://user-images.githubusercontent.com/64180387/140900904-0013414d-59ed-407a-ab9f-41300d1a8adb.png)

**Comment by Xyuan-abs** [comment]
版本是vue-cropper-h5 2.0.0

**Comment by Xyuan-abs** [comment]
是不是没有把方法暴露出来

**Comment by Xyuan-abs** [comment]
![image](https://user-images.githubusercontent.com/64180387/141028178-270060f8-ae76-40d1-9406-db2e88887972.png)
ref获取到的实例上没有loadFile这个方法

**Comment by 2277419213** [comment]
稍等我一下，我来修复下，预计11月10号9点30前修复

**Comment by Xyuan-abs** [comment]
> 稍等我一下，我来修复下，预计11月10号9点30前修复

感谢大佬

**Comment by 2277419213** [comment]
发布了用2.0.1版本试试

**Comment by Xyuan-abs** [comment]
可以了，再次感谢大佬


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: 居里栈栈 ***@***.***&gt;
发送时间: 2021年11月10日 09:34
收件人: 2277419213/vue-cropper-h5 ***@***.***&gt;
抄送: Xyuan-abs ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[2277419213/vue-cropper-h5] vue3调用loadFile方法时报loadFile is not a function (Issue #41)





 
发布了用2.0.1版本试试
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
