### ISSUE TITLE
关于截图后生成的图片格式及名称问题

### ISSUE THREAD

**Issue by Xyuan-abs** [2277419213/vue-cropper-h5#47]
在使用getFile获取截图后的图片时，生成的文件名是随机的吗？格式目前是固定成png，可以实现跟传入图片的格式同步吗

**Comment by 2277419213** [comment]
格式是传进去的，通过outputType去控制
生成的文件名是单前的时间戳

**Comment by Xyuan-abs** [comment]
> 格式是传进去的，通过outputType去控制 生成的文件名是单前的时间戳

我的，没认真看文档
