### ISSUE TITLE
为什么裁剪后的图片 那么模糊了。。

### ISSUE THREAD

**Issue by a6965921** [2277419213/vue-cropper-h5#48]
为什么裁剪后的图片 那么模糊了。。
我上传1082px*6744px  截图出来的base64 就是很糊 上面的文字都看不清  但是 我上传1080px*1500px  截图出来的就是很清晰

仔细看了下 我上传1082px*6744px  是上传以后 生成的blob图片宽度和高度等比例缩小了 变成宽度320了

**Comment by 2277419213** [comment]
你可以试试这几个参数
full	是否输出原图比例的截图
high	是否按照设备的 dpr 输出等比例图片
original	上传图片按照原始比例渲染
