### ISSUE TITLE
能添加对heic格式图片的支持吗

### ISSUE THREAD

**Issue by Xyuan-abs** [2277419213/vue-cropper-h5#49]
现在导入heic格式图片 展示不出来
![image](https://user-images.githubusercontent.com/64180387/159659453-b39c21e9-8005-4e89-9e02-2f2f95c14833.png)

**Comment by 2277419213** [comment]
HEIC格式的图片目前Chrome等浏览器还不支持自动解析
你可以选择自己服务器转换一下
