### ISSUE TITLE
页面有canvas 加载图片就很慢 一直黑屏  要吧canvas删掉才快

### ISSUE THREAD

**Issue by a6965921** [2277419213/vue-cropper-h5#54]
页面有canvas 加载图片就很慢 一直黑屏  要吧canvas删掉才快 这个怎么解决

**Comment by 2277419213** [comment]
这个是canvas冲突了嘛，你页面的canvas实际作用是啥，可以v-if隐藏的嘛

**Comment by a6965921** [comment]
我里面有pixijs渲染的动画  具体哪个冲突我也没试过
