### ISSUE TITLE
ios 12.0 拍照之后确定 会刷新页面

### ISSUE THREAD

**Issue by weblowb** [2277419213/vue-cropper-h5#8]

**Comment by 2277419213** [comment]
我怀疑你遇到了杀后台最严重的ios 12.4.1，因为跳转到原生相册，系统就把微信后台杀了， 你可以写个最简单的上传试下<input type="file" accept="image/*"/>，如果这个也会刷新页面，那你基本无解了，唯一的解决办法就是调用微信的jsdk，用jsdk去选择照片，然后传入照片地址，配合hide-input食用
